version: "3.8"

services:
  backend:
    build: ./Ri2S-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ibt
    depends_on:
      - mongodb
  frontend:
    build: ./RI2S-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27013:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
